title       = "Guàrdia Documentation"
project     = "guardia"
description = "Some really easy guards for Lua & MoonScript"
format      = "markdown"
dir         = "docs"
topics      = {"README.md", "README-V1.md"}
examples    = {"examples", exclude = {"examples/antierrguard.lua", "examples/biguard.lua", "examples/endguard.lua", "examples/guard.lua", "examples/v2_tests.lua"}}
file        = {"guardia"}
